import React from 'react';

const About = ()=> {
    return(
        <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet purus gravida quis blandit turpis cursus. Facilisis leo vel fringilla est. Purus in mollis nunc sed. Magnis dis parturient montes nascetur ridiculus mus. Viverra accumsan in nisl nisi scelerisque eu ultrices. Amet consectetur adipiscing elit duis tristique sollicitudin nibh sit. Tempor nec feugiat nisl pretium fusce id velit. Amet commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Bibendum neque egestas congue quisque egestas diam in arcu. Faucibus purus in massa tempor nec feugiat nisl. Faucibus a pellentesque sit amet porttitor. In fermentum posuere urna nec. Faucibus vitae aliquet nec ullamcorper. Massa vitae tortor condimentum lacinia quis vel eros. Integer quis auctor elit sed vulputate mi sit amet. Ultrices eros in cursus turpis massa tincidunt dui ut. Enim neque volutpat ac tincidunt vitae semper quis.

        Pretium aenean pharetra magna ac placerat vestibulum lectus. Diam maecenas sed enim ut sem viverra. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Malesuada proin libero nunc consequat interdum varius sit amet. Sit amet commodo nulla facilisi nullam vehicula ipsum a. Diam ut venenatis tellus in metus vulputate eu. Ut etiam sit amet nisl purus. Ac auctor augue mauris augue. Elit ut aliquam purus sit amet. Ut enim blandit volutpat maecenas volutpat blandit aliquam. Proin sagittis nisl rhoncus mattis rhoncus urna neque. Volutpat consequat mauris nunc congue nisi vitae. Lorem sed risus ultricies tristique nulla aliquet enim tortor. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Nisl tincidunt eget nullam non.
        
        Bibendum arcu vitae elementum curabitur vitae nunc sed velit. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Ultrices sagittis orci a scelerisque purus semper eget duis. Rhoncus urna neque viverra justo nec ultrices. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque. Ullamcorper dignissim cras tincidunt lobortis feugiat. Elit ullamcorper dignissim cras tincidunt lobortis. Felis eget velit aliquet sagittis id consectetur. Turpis egestas maecenas pharetra convallis posuere morbi leo urna molestie. Netus et malesuada fames ac turpis egestas integer eget aliquet. Nisi vitae suscipit tellus mauris a. Dolor sed viverra ipsum nunc. Scelerisque eu ultrices vitae auctor. Nisi lacus sed viverra tellus in. Congue quisque egestas diam in arcu cursus euismod quis viverra. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus.
        
        Nibh tortor id aliquet lectus. Amet consectetur adipiscing elit ut aliquam. Cursus mattis molestie a iaculis. Ultrices in iaculis nunc sed augue lacus viverra vitae. Urna porttitor rhoncus dolor purus non enim. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Sit amet consectetur adipiscing elit ut aliquam purus sit. Magna etiam tempor orci eu lobortis elementum nibh. Fermentum leo vel orci porta. Facilisis gravida neque convallis a cras semper auctor neque vitae.
        
        Quis varius quam quisque id. Hac habitasse platea dictumst vestibulum rhoncus est. Venenatis urna cursus eget nunc scelerisque viverra mauris. Nulla malesuada pellentesque elit eget gravida cum. Ac turpis egestas maecenas pharetra. At elementum eu facilisis sed odio. Hac habitasse platea dictumst quisque sagittis purus sit amet. Curabitur gravida arcu ac tortor dignissim. Semper risus in hendrerit gravida. Non curabitur gravida arcu ac. Egestas sed tempus urna et pharetra pharetra massa. Vitae justo eget magna fermentum iaculis eu non diam. A erat nam at lectus urna. Nunc faucibus a pellentesque sit amet porttitor eget dolor morbi. Aliquam ut porttitor leo a diam sollicitudin tempor id.</div>
    );
};
export default About;